import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Nav from "./Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lecture 12 homework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        <div className="grid grid-rows-layout grid-cols-layout min-h-screen">
          <Header />
          <Nav />
          <aside className="bg-gray-100 p-4">Aside</aside>
          <main className="bg-white p-4">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}